### PR TITLE
Add macports curl-ca-bundle support (path)

### LINKED ISSUE #13: Support macports
Using the macports package management system on MacOS, the SSL certificates are installed by the package `curl-ca-bundle` in the file `/opt/local/share/curl/curl-ca-bundle.crt` (they also install a symlink to that as `/opt/local/etc/openssl/cert.pem`.

Would it be possible to add `/opt/local/etc/openssl` to the list of directories in openssl-probe's `find_certs_dirs`?

### PR DESCRIPTION
**Pull request by khorolets**
Closes #13

### CODE REVIEW

**Comment by khorolets** [comment]
@alexcrichton thanks for fast merging, can you give any estimation on how long would it take to get the patch to the crates.io? Thanks!

**Comment by alexcrichton** [comment]
I've published 0.1.3 with these changes now!

**Comment by alexcrichton** [comment]
Sorry I had to yank due to a breaking change -- https://github.com/alexcrichton/openssl-probe/issues/16 -- I don't really have time to manage this crate right now :(

**Comment by frol** [comment]
@alexcrichton may we ask to release 0.2.0 version?

**Pull request merged**
